# Generated by Django 3.2.7 on 2021-11-29 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Seeker', '0002_auto_20211129_1619'),
        ('Company', '0002_auto_20211129_1619'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Job',
        ),
    ]
