# Generated by Django 3.2.7 on 2021-11-29 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0002_auto_20211129_1619'),
        ('Seeker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=50, unique=True)),
                ('city', models.CharField(max_length=20)),
                ('id_proof', models.FileField(upload_to='media/documents')),
                ('c_pic', models.FileField(upload_to='media/images')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company.user')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jpost', models.CharField(max_length=50)),
                ('jduration', models.CharField(max_length=50)),
                ('jdesc', models.TextField(max_length=1000)),
                ('jsalary', models.CharField(max_length=50)),
                ('jtags', models.TextField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seeker.company')),
            ],
        ),
        migrations.AlterField(
            model_name='applyjob',
            name='job_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seeker.job'),
        ),
        migrations.AlterField(
            model_name='savedjob',
            name='job_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seeker.job'),
        ),
    ]
