# Generated by Django 3.2.7 on 2021-11-29 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0004_company'),
        ('Seeker', '0002_auto_20211129_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='company_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company.company'),
        ),
        migrations.DeleteModel(
            name='Company',
        ),
    ]
