# Generated by Django 3.2.7 on 2021-12-17 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0004_company'),
        ('Seeker', '0007_joblike'),
    ]

    operations = [
        migrations.CreateModel(
            name='Following',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company.company')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company.user')),
            ],
        ),
    ]
