# Generated by Django 3.2.7 on 2021-12-17 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Seeker', '0008_following'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Following',
        ),
    ]
