# Generated by Django 3.2.7 on 2021-12-18 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Seeker', '0010_following'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seeker.project')),
                ('seeker_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seeker.seeker')),
            ],
        ),
    ]
