# Generated by Django 3.2.7 on 2021-12-25 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Seeker', '0014_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
