# Generated by Django 3.2.7 on 2021-12-25 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Seeker', '0015_delete_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seeker_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seeker.seeker')),
            ],
        ),
    ]
