# Generated by Django 3.2.7 on 2021-12-26 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seeker', '0016_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='facebook',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='link',
            name='instagram',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='link',
            name='pinterest',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='link',
            name='twitter',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='link',
            name='youtube',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
