# Generated by Django 3.2.7 on 2021-12-26 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Seeker', '0017_auto_20211226_1150'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Link',
        ),
    ]
