# Generated by Django 3.2.7 on 2021-12-26 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Seeker', '0019_link'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Link',
        ),
    ]
